#!/bin/bash

# Check if at least two arguments are provided
if [[ $# -lt 2 ]]; then
  echo "Usage: aoc <part> <input>"
  exit 1
fi

# Validate that both arguments are numbers
if ! [[ "$1" =~ ^[0-9]+$ ]] || ! [[ "$2" =~ ^[0-9]+$ ]]; then
  echo "Error: both arguments must be numbers"
  exit 1
fi

file="part$1.cpp"

LTIME=`stat -c %Z $file`

while true; do
    printf '%*s' $COLUMNS | tr ' ' '-'
    echo "Watching $file for changes..."
    sleep 1
    
    # # Compile the source
    # clang++ -o main \
    #     -std=c++20 \
    #     -O3 \
    #     -I/home/akos/cpp-include/ \
    #     "part$1.cpp"
    #
    # # Run the executable with the provided input
    # time ./main < "input.$2"
done

