#!/bin/bash

task_ids="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
folder_name=$1
task_count=$(( $2 ))

mkdir $folder_name
cd $folder_name

for (( i=0; i<task_count; i++ )); do
    task_id="${task_ids:i:1}"
    mkdir $task_id
    cp $HOME/.config/nvim/templates/contest-template.cpp $task_id/_main.cpp
done

nvim .
