#!/bin/bash

# Loop through all files named "_main.cpp" in the current directory and subdirectories
find . -type f -name "_main.cpp" | while read -r file; do
    # Get the directory of the file
    dir=$(dirname "$file")
    # Rename the file to "main.cpp" in the same directory
    mv "$file" "$dir/main.cpp"
    echo "Renamed: $file -> $dir/main.cpp"
done

echo "All matching files have been renamed."

